dataset:
  train:
    - data_dir: ../data/p_cable_splitted_dataset/train
      bg_paths: null
      w_aug: true
      percentage: 1
  test:
    data_dir: ../data/refined_cable_dataset/test
    bg_paths: null
    w_aug: false
  